---
- hosts: all
  remote_user: root
  vars_files: 
          - "../vars/{{env}}_vars.yml"
          - "../vars/{{env}}_vault.yml"
  roles: 
          - role: create_user
          - role: install_apache

